# Human Stress Prediction

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("C:\\Users\\saipr\\Downloads\\SaYoPillow.csv")

In [3]:
df

sr      rr       t      lm      bo     rem   sr.1     hr  sl
0    93.800  25.680  91.840  16.600  89.840   99.60  1.840  74.20   3
1    91.640  25.104  91.552  15.880  89.552   98.88  1.552  72.76   3
2    60.000  20.000  96.000  10.000  95.000   85.00  7.000  60.00   1
3    85.760  23.536  90.768  13.920  88.768   96.92  0.768  68.84   3
4    48.120  17.248  97.872   6.496  96.248   72.48  8.248  53.12   0
..      ...     ...     ...     ...     ...     ...    ...    ...  ..
625  69.600  20.960  92.960  10.960  90.960   89.80  3.440  62.40   2
626  48.440  17.376  98.064   6.752  96.376   73.76  8.376  53.44   0
627  97.504  27.504  86.880  17.752  84.256  101.88  0.000  78.76   4
628  58.640  19.728  95.728   9.728  94.592   84.32  6.728  59.32   1
629  73.920  21.392  93.392  11.392  91.392   91.96  4.088  63.48   2

[630 rows x 9 columns]

In [4]:
df.rename(columns={'sr.1': 'sr_1'}, inplace=True)


In [5]:
df.isnull().sum()

sr      0
rr      0
t       0
lm      0
bo      0
rem     0
sr_1    0
hr      0
sl      0
dtype: int64

In [6]:
df

sr      rr       t      lm      bo     rem   sr_1     hr  sl
0    93.800  25.680  91.840  16.600  89.840   99.60  1.840  74.20   3
1    91.640  25.104  91.552  15.880  89.552   98.88  1.552  72.76   3
2    60.000  20.000  96.000  10.000  95.000   85.00  7.000  60.00   1
3    85.760  23.536  90.768  13.920  88.768   96.92  0.768  68.84   3
4    48.120  17.248  97.872   6.496  96.248   72.48  8.248  53.12   0
..      ...     ...     ...     ...     ...     ...    ...    ...  ..
625  69.600  20.960  92.960  10.960  90.960   89.80  3.440  62.40   2
626  48.440  17.376  98.064   6.752  96.376   73.76  8.376  53.44   0
627  97.504  27.504  86.880  17.752  84.256  101.88  0.000  78.76   4
628  58.640  19.728  95.728   9.728  94.592   84.32  6.728  59.32   1
629  73.920  21.392  93.392  11.392  91.392   91.96  4.088  63.48   2

[630 rows x 9 columns]

In [7]:
#splitting the data into training and testing sets
X=df.drop('sl',axis=1)
y=df['sl']

In [8]:
X

sr      rr       t      lm      bo     rem   sr_1     hr
0    93.800  25.680  91.840  16.600  89.840   99.60  1.840  74.20
1    91.640  25.104  91.552  15.880  89.552   98.88  1.552  72.76
2    60.000  20.000  96.000  10.000  95.000   85.00  7.000  60.00
3    85.760  23.536  90.768  13.920  88.768   96.92  0.768  68.84
4    48.120  17.248  97.872   6.496  96.248   72.48  8.248  53.12
..      ...     ...     ...     ...     ...     ...    ...    ...
625  69.600  20.960  92.960  10.960  90.960   89.80  3.440  62.40
626  48.440  17.376  98.064   6.752  96.376   73.76  8.376  53.44
627  97.504  27.504  86.880  17.752  84.256  101.88  0.000  78.76
628  58.640  19.728  95.728   9.728  94.592   84.32  6.728  59.32
629  73.920  21.392  93.392  11.392  91.392   91.96  4.088  63.48

[630 rows x 8 columns]

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [11]:
#Preprocessing
from sklearn.preprocessing import StandardScaler

In [12]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [13]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [14]:
#Predictions
predictions=model.predict(X_test)

In [15]:
predictions

array([0, 3, 2, 0, 3, 2, 3, 1, 0, 0, 2, 4, 2, 2, 1, 4, 1, 4, 1, 2, 0, 0,
       4, 0, 0, 2, 4, 0, 2, 2, 2, 0, 2, 2, 4, 0, 3, 2, 2, 3, 4, 4, 1, 0,
       4, 1, 1, 3, 3, 3, 1, 3, 2, 3, 0, 1, 0, 1, 3, 0, 3, 3, 0, 2, 0, 1,
       4, 2, 3, 0, 2, 3, 1, 4, 3, 4, 3, 1, 2, 3, 3, 4, 3, 4, 1, 4, 2, 2,
       1, 3, 4, 1, 2, 4, 4, 2, 4, 4, 2, 4, 4, 0, 1, 2, 1, 1, 0, 1, 3, 1,
       2, 4, 1, 3, 0, 0, 1, 0, 4, 0, 2, 3, 2, 2, 4, 3, 0, 0, 1, 2, 1, 0,
       3, 0, 2, 0, 0, 0, 2, 1, 2, 4, 2, 0, 4, 0, 1, 1, 0, 1, 3, 0, 4, 3,
       3, 4, 3, 1, 3, 2, 0, 0, 2, 2, 4, 2, 4, 1, 1, 1, 0, 3, 4, 2, 1, 0,
       4, 2, 0, 3, 3, 1, 4, 4, 2, 3, 4, 1, 3], dtype=int64)

In [16]:
y_test

497    0
244    3
552    2
213    0
549    3
      ..
92     2
499    3
68     4
15     1
199    3
Name: sl, Length: 189, dtype: int64

In [17]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [18]:
print(confusion_matrix(y_test,predictions))

[[39  0  0  0  0]
 [ 1 35  0  0  0]
 [ 0  1 40  0  0]
 [ 0  0  1 36  0]
 [ 0  0  0  0 36]]


In [19]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.97      1.00      0.99        39
           1       0.97      0.97      0.97        36
           2       0.98      0.98      0.98        41
           3       1.00      0.97      0.99        37
           4       1.00      1.00      1.00        36

    accuracy                           0.98       189
   macro avg       0.98      0.98      0.98       189
weighted avg       0.98      0.98      0.98       189



In [20]:
print("Test Accuracy:", accuracy_score(y_test, predictions))


Test Accuracy: 0.9841269841269841


In [21]:
data={
    'sr':[93.800],
    'rr':[25.680],
    't':[91.840],
    'lm':[16.600],
    'bo':[89.840],
    'rem':[99.60],
    'sr_1':[1.840],
    'hr':[74.20]
}
new_df=pd.DataFrame(data)

In [22]:
# Standardize the new data point using the fitted scaler
new_df_scaled = scaler.transform(new_df)

In [23]:
# Predict using the standardized new data point
y_new_pred = model.predict(new_df_scaled)


In [24]:
print("Predicted Class:", y_new_pred[0])


Predicted Class: 3


In [25]:
data1={
    'sr':[97.504],
    'rr':[27.504],
    't':[86.880],
    'lm':[17.752],
    'bo':[84.256],
    'rem':[101.88],
    'sr_1':[0.000],
    'hr':[78.76]
}
new_df1=pd.DataFrame(data1)
# Standardize the new data point using the fitted scaler
new_df_scaled1 = scaler.transform(new_df1)
# Predict using the standardized new data point
y_new_pred1 = model.predict(new_df_scaled1)
print("Predicted Class:", y_new_pred1[0])


Predicted Class: 4


In [26]:
import joblib
# Save the model
joblib.dump(model, 'model.pkl')


['model.pkl']